hhservice/web/views/accounts.py
from flask import Blueprint, render_template, g, url_for, redirect, session
from flask_login import login_user, logout_user, login_required, current_user

from hhservice.web import forms
from hhservice.web.acl import User

module = Blueprint('accounts', __name__)


@module.route('/login', methods=('GET', 'POST'))
def login():
    if current_user.is_authenticated:
        return redirect(url_for('dashboard.index'))

    form = forms.accounts.LoginForm()

    if not form.validate_on_submit():
        return render_template('accounts/login.html',
                               form=form)

    name = form.name.data
    password = form.password.data
    c = g.hhclient
    auth = c.authenticate(name=name, password=password)
    if auth.is_error:
        return render_template('accounts/login.html',
                               form=form,
                               errors=auth.errors)

    user = c.users.get(auth.data['user']['id'])
    buildings = c.buildings.list()

    session['token'] = auth.data
    session['user'] = user.data
    session['buildings'] = [building.data for building in buildings]

    user = User(**user.data)

    login_user(user)

    return redirect(url_for('dashboard.index'))


@module.route("/logout")
@login_required
def logout():
    session.pop('token', None)
    session.pop('user', None)
    session.pop('buildings', None)
    logout_user()
    return redirect(url_for('site.index'))


@module.route('/register', methods=('GET', 'POST'))
def register():
    form = forms.accounts.RegisterForm()
    if not form.validate_on_submit():
        return render_template('accounts/register.html',
                               form=form)

    c = g.hhclient

    response = c.users.create(**form.data)
    if response.is_error:
        return render_template('accounts/register.html',
                               form=form,
                               errors=response.errors)

    return render_template('accounts/register_success.html')

hhservice/web/views/site.py
from flask import Blueprint, render_template


module = Blueprint('site', __name__)


@module.route('/')
def index():
    return render_template('/site/index.html')

hhservice/web/templates/base/banner.html
    <div class="section no-pad-bot" id="index-banner">
        <div class="container">
            <br><br>
            <h1 class="header center orange-text">Home Hero</h1>
            <div class="row center">
                <h5 class="header col s12 light">Smart Home, Intelligent Living in Smart Cities</h5>
            </div>
            <div class="row center">
                <a href="#" id="download-button" class="btn-large waves-effect waves-light orange">About</a>
            </div>
            <br><br>

        </div>
    </div>

hhservice/web/templates/base/base-layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
    <title>{% block title  %}Home Hero{% endblock %}</title>
    <script src="/static/jspm_packages/system.js"></script>
    <script src="/static/config.js"></script>
    <script type="text/javascript">
      {% block jsmodule %}
      System.import('css-framework').then(() => {
          System.import('main'); 
      });
      {% endblock %}
    </script>
    {% block additional_head %}{% endblock %}
  </head>

  <body>
    <header> 
    {% block header %}
      {% include "/base/toolbar.html" %}
      {% if request.path == url_for('site.index') %}
        {% include "/base/banner.html" %}
      {% else %}
        <div style="padding-top:50px;"></div>
      {% endif %}
    {% endblock %}
    </header>

    <main>
    {% block main %}{% endblock %}
    </main>

    <footer>
      {% include "/base/footer.html" %}
    </footer>
  </body>
</html>

hhservice/web/templates/base/default-dashboard.html
{% extends "/base/base-layout.html" %}

{% block title %}Home Hero Dashboard{% endblock %}

{% block jsmodule %}
System.import('css-framework').then(() => {
                System.import('dashboard'); 
            });
{% endblock %}
{% block additional_head %}
<style>
  header, main, footer {
        padding-left: 300px;
    }

    @media only screen and (max-width : 992px) {
        header, main, footer {
        padding-left: 0;
      }
  }
  .collapsible li.active i#more {
    -ms-transform: rotate(180deg); /* IE 9 */
    -webkit-transform: rotate(180deg); /* Chrome, Safari, Opera */
    transform: rotate(180deg);
  }
</style>
{% endblock additional_head %}

{% block header %}
  {% include "/base/toolbar-dashboard.html" %}
{% endblock %}

{% block main %}
  <div class="container">
    <div class="row">
      <nav>
        <div class="nav-wrapper orange">
          <div class="col s12">
            <a href="{{ url_for('dashboard.index') }}" class="breadcrumb">Dashboard</a>
            {% block breadcrumbs %}{% endblock %}
          </div>
        </div>
      </nav>
    </div>
  </div>
 
  <div class="container">           
    {% block content %}{% endblock %}
  </div>
{% endblock %}

hhservice/web/templates/base/default-page.html
{% extends "/base/base-layout.html" %}
{% block main %}
  <div class="container">
    {% block content %}{% endblock content %}
  </div>
{% endblock %}

hhservice/web/templates/base/error-handler.html
{% macro get_validate_class(errors) -%}
{%- set class_str = 'validate' -%}
{% if errors | count > 0 -%}
{% set class_str = class_str + ' ' + 'invalid' %}
{%- endif %}
{{- class_str -}}
{%- endmacro %}

{% macro get_error_messages(errors) -%}
{{ errors | join(', ') }}
{%- endmacro %}

hhservice/web/templates/base/footer.html
  
  <div class="page-footer orange">
    <div class="container">
      <div class="row">

        <div class="col l6 s12">
          <h5 class="white-text">Home Hero</h5>
          <p class="grey-text text-lighten-4">Home Hero is a project under UoT@Tech working groub. Urban IoT or UoT@Tech is a multidisciplinary R&D workgroup that focuses on Intelligent Living in Smart Cities. That is to say our main objective is to improve everyday life in society with technology and smartness surrounding people in their household forming interconnected neighborhood within their city.</p>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Interesting</h5>
          <ul>
            <li><a class="white-text" href="http://iot.latech.edu/">UoT@Tech</a></li>
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Connect</h5>
          <ul>
            <li><a class="white-text" href="http://iot.latech.edu/">UoT@Tech</a></li>
          </ul>
        </div>

      </div>
    </div>

    <div class="footer-copyright">
      <div class="container">
        UoT@Tech
      </div>
    </div>
  </div>

hhservice/web/templates/base/toolbar-dashboard.html
<ul id="slide-out" class="side-nav fixed">
    <li>
        <div class="userView" style="background-color: #fb8c00;">
            {#
            <div class="background">
                <img src="images/office.jpg">
            </div>
            #}
            {#
            <a href="#!user"><img class="circle" src="images/yuna.jpg"></a>
            #}
            <a href="#!name"><span class="white-text name">{{ current_user.first_name }} {{ current_user.last_name }}</span></a>
            <a href="#!email"><span class="white-text email">{{ current_user.email }}</span></a>
        </div>
    </li>
    <li><a href="{{ url_for('dashboard.index') }}"><i class="material-icons">dashboard</i>Dashboard</a></li>
    <li>
      <ul class="collapsible" data-collapsible="accordion" style="padding-left:16px;">
        <li><a class="collapsible-header waves-effect waves-cyan"><i class="material-icons">home</i>Buildings <i class="material-icons right" id="more">expand_more</i></a>
          <div class="collapsible-body">
            <ul>
              {% for building in session.get('buildings', []) %}
              <li><a style="padding-left:32px;" href="{{ url_for('dashboard.buildings.view', building_id=building['id']) }}"><i class="material-icons">home</i>{{ building['name'] }}</a></li>
              {% endfor %}
              <li><a style="padding-left:32px;" href="{{ url_for('dashboard.buildings.create') }}"><i class="material-icons">create</i>Create</a></li>
            </ul>
          </div>
        </li>
      </ul>
    </li>
    {# 
      <li><a href="{{ url_for('dashboard.applications.index') }}"><i class="material-icons">extension</i>Applications</a></li>
    <li><a href="#!">Second Link</a></li>
    <li><div class="divider"></div></li>
    <li><a class="subheader">Tools</a></li>
    <li><a class="waves-effect" href="">xxx</a></li>
    #}
    <li><a href="{{ url_for('accounts.logout') }}"><i class="material-icons">exit_to_app</i>Logout</a></li>
</ul>
                    
{# end slide-out menu #}

<div class="row">
    <div class="col s12 m12" style="padding-left:0px;">
        <nav class="grey darken-3">
            <div class="nav-wrapper">    
                <a href="#" data-activates="slide-out" class="button-collapse"><i class="material-icons">menu</i></a>
                <span style="padding-left:10px;">
                    <a href="{{ url_for('dashboard.index') }}" class="brand-logo"><i class="material-icons">dashboard</i>Home Hero Dashboard</a>
                </span>
                <ul class="right hide-on-med-and-down">
                    <li><a href="sass.html"><i class="material-icons">search</i></a></li>
                    <li><a href="badges.html"><i class="material-icons">view_module</i></a></li>
                    <li><a href="collapsible.html"><i class="material-icons">refresh</i></a></li>
                    <li><a href="mobile.html"><i class="material-icons">more_vert</i></a></li>
                </ul>
            </div>
        </nav>
    </div>
</div>

hhservice/web/templates/base/toolbar.html
{% macro navlink() -%}
  {% if current_user.is_authenticated %}
    <li><a href="{{ url_for('dashboard.index') }}">Dashboard</a></li>
    <li><a href="{{ url_for('accounts.logout') }}">Logout</a></li>
  {% else %}
    <li><a href="{{ url_for('accounts.login') }}">Login</a></li>
    <li><a href="{{ url_for('accounts.register') }}">Register</a></li>
  {% endif %}
{% endmacro %}


  <nav class="light-blue lighten-1" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="/" class="brand-logo"><i class="material-icons">home</i> Home Hero</a>
      <ul class="right hide-on-med-and-down">
          {{ navlink() }}
      </ul>

      <ul id="nav-mobile" class="side-nav">
          {{ navlink() }}
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>